codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 2%
    patch:
      default:
        target: 80%

ignore:
  - "*/tests/*"
  - "*/migrations/*"
  - "rivaflow/cli/*"
