"""Wave 3 batch 2 — snapshot-backed /summary (pure; DB + today_is_rest_day mocked).

whoop_summary() costs ~35s live (readiness + prevention + per-session Banister
loads). Wave 2.2 already stores the exact same JSON contract in
whoop_cockpit_snapshot.metrics_json, regenerated by the scheduler every few
hours. `_summary_from_snapshot` reads that instead when it's fresh and its
baked-in sabbath state agrees with today; otherwise both /summary call sites
(the Bearer route and the api-key /view route) fall back to the unchanged
live path via `_live_summary`.
"""

from __future__ import annotations

import asyncio
import json
import logging
from datetime import UTC, datetime, timedelta

from rivaflow.api.routes import whoop as whoop_route
from rivaflow.db.repositories.whoop_repo import WhoopRepository

FRESH_METRICS = {
    "readiness": {"state": "Prime", "score": 87, "headline": "green light to push"},
    "hrv_today": {"rmssd": 57},
    "resting_hr_today": {"resting_hr": 50},
    "sleep": {"available": True, "duration_hours": 7.6, "quality_score": 84},
}


def _snapshot_row(*, age: timedelta, metrics: dict | None = FRESH_METRICS) -> dict:
    rendered_at = datetime.now(UTC) - age
    return {
        "metrics_json": json.dumps(metrics) if metrics is not None else None,
        "deriver_version": "v3",
        "rendered_at": rendered_at,
    }


def _no_rest_day(_user_id: int) -> bool:
    return False


def _is_rest_day(_user_id: int) -> bool:
    return True


# ── _summary_from_snapshot ──────────────────────────────────────────────


def test_fresh_snapshot_served_with_source_and_as_of(monkeypatch):
    row = _snapshot_row(age=timedelta(minutes=5))
    monkeypatch.setattr(
        WhoopRepository, "get_cockpit_metrics", staticmethod(lambda uid: row)
    )
    monkeypatch.setattr(whoop_route, "today_is_rest_day", _no_rest_day)

    result = whoop_route._summary_from_snapshot(1)

    assert result is not None
    assert result["source"] == "snapshot"
    assert result["as_of"] == row["rendered_at"].isoformat()
    assert result["readiness"]["state"] == "Prime"


def test_stale_snapshot_falls_back_to_none(monkeypatch):
    row = _snapshot_row(age=timedelta(hours=4, minutes=1))
    monkeypatch.setattr(
        WhoopRepository, "get_cockpit_metrics", staticmethod(lambda uid: row)
    )
    monkeypatch.setattr(whoop_route, "today_is_rest_day", _no_rest_day)

    assert whoop_route._summary_from_snapshot(1) is None


def test_snapshot_exactly_at_ceiling_is_still_fresh(monkeypatch):
    # 4h ceiling is inclusive — only strictly older is stale.
    row = _snapshot_row(age=timedelta(hours=3, minutes=59))
    monkeypatch.setattr(
        WhoopRepository, "get_cockpit_metrics", staticmethod(lambda uid: row)
    )
    monkeypatch.setattr(whoop_route, "today_is_rest_day", _no_rest_day)

    assert whoop_route._summary_from_snapshot(1) is not None


def test_missing_row_falls_back_to_none(monkeypatch):
    monkeypatch.setattr(
        WhoopRepository, "get_cockpit_metrics", staticmethod(lambda uid: None)
    )
    monkeypatch.setattr(whoop_route, "today_is_rest_day", _no_rest_day)

    assert whoop_route._summary_from_snapshot(1) is None


def test_row_without_metrics_json_falls_back_to_none(monkeypatch):
    row = _snapshot_row(age=timedelta(minutes=1), metrics=None)
    monkeypatch.setattr(
        WhoopRepository, "get_cockpit_metrics", staticmethod(lambda uid: row)
    )
    monkeypatch.setattr(whoop_route, "today_is_rest_day", _no_rest_day)

    assert whoop_route._summary_from_snapshot(1) is None


def test_malformed_json_falls_back_to_none_and_logs_warning(monkeypatch, caplog):
    row = {
        "metrics_json": "{not valid json",
        "deriver_version": "v3",
        "rendered_at": datetime.now(UTC),
    }
    monkeypatch.setattr(
        WhoopRepository, "get_cockpit_metrics", staticmethod(lambda uid: row)
    )
    monkeypatch.setattr(whoop_route, "today_is_rest_day", _no_rest_day)

    with caplog.at_level(logging.WARNING, logger=whoop_route.logger.name):
        result = whoop_route._summary_from_snapshot(1)

    assert result is None
    assert any(
        "unparseable" in rec.message.lower() and rec.levelno == logging.WARNING
        for rec in caplog.records
    )


def test_sabbath_mismatch_today_is_rest_snapshot_is_not(monkeypatch):
    # Today is the rest day, but the snapshot (built yesterday evening) has a
    # non-Rest readiness — a Saturday-evening snapshot served Sunday morning.
    row = _snapshot_row(age=timedelta(minutes=10), metrics=FRESH_METRICS)
    monkeypatch.setattr(
        WhoopRepository, "get_cockpit_metrics", staticmethod(lambda uid: row)
    )
    monkeypatch.setattr(whoop_route, "today_is_rest_day", _is_rest_day)

    assert whoop_route._summary_from_snapshot(1) is None


def test_sabbath_mismatch_snapshot_is_rest_today_is_not(monkeypatch):
    # Reverse direction — snapshot says Rest, but today is not the rest day.
    rest_metrics = {**FRESH_METRICS, "readiness": {"state": "Rest", "score": None}}
    row = _snapshot_row(age=timedelta(minutes=10), metrics=rest_metrics)
    monkeypatch.setattr(
        WhoopRepository, "get_cockpit_metrics", staticmethod(lambda uid: row)
    )
    monkeypatch.setattr(whoop_route, "today_is_rest_day", _no_rest_day)

    assert whoop_route._summary_from_snapshot(1) is None


def test_sabbath_states_agree_snapshot_is_served(monkeypatch):
    rest_metrics = {**FRESH_METRICS, "readiness": {"state": "Rest", "score": None}}
    row = _snapshot_row(age=timedelta(minutes=10), metrics=rest_metrics)
    monkeypatch.setattr(
        WhoopRepository, "get_cockpit_metrics", staticmethod(lambda uid: row)
    )
    monkeypatch.setattr(whoop_route, "today_is_rest_day", _is_rest_day)

    result = whoop_route._summary_from_snapshot(1)
    assert result is not None
    assert result["source"] == "snapshot"


# ── _live_summary ───────────────────────────────────────────────────────


def test_live_summary_carries_source_and_as_of(monkeypatch):
    monkeypatch.setattr(whoop_route, "today_is_rest_day", _no_rest_day)
    monkeypatch.setattr(
        whoop_route,
        "_timed_whoop_summary",
        lambda uid, today_is_sabbath: {"readiness": {"state": "Balanced"}},
    )

    result = whoop_route._live_summary(1)

    assert result["source"] == "live"
    assert "as_of" in result
    # Round-trips through fromisoformat without raising.
    datetime.fromisoformat(result["as_of"])
    assert result["readiness"]["state"] == "Balanced"


# ── route-level: /summary (Bearer call site) ────────────────────────────


def test_summary_route_uses_snapshot_when_fresh(monkeypatch):
    row = _snapshot_row(age=timedelta(minutes=5))
    monkeypatch.setattr(
        WhoopRepository, "get_cockpit_metrics", staticmethod(lambda uid: row)
    )
    monkeypatch.setattr(whoop_route, "today_is_rest_day", _no_rest_day)

    def _boom(uid, today_is_sabbath):
        raise AssertionError("live path should not run when snapshot is fresh")

    monkeypatch.setattr(whoop_route, "_timed_whoop_summary", _boom)

    # @route_error_handler always wraps the route in an async wrapper.
    result = asyncio.run(whoop_route.summary(current_user={"id": 1}))

    assert result["source"] == "snapshot"
    assert result["readiness"]["state"] == "Prime"


def test_summary_route_falls_back_to_live_when_snapshot_missing(monkeypatch):
    monkeypatch.setattr(
        WhoopRepository, "get_cockpit_metrics", staticmethod(lambda uid: None)
    )
    monkeypatch.setattr(whoop_route, "today_is_rest_day", _no_rest_day)
    monkeypatch.setattr(
        whoop_route,
        "_timed_whoop_summary",
        lambda uid, today_is_sabbath: {"readiness": {"state": "Building"}},
    )

    result = asyncio.run(whoop_route.summary(current_user={"id": 1}))

    assert result["source"] == "live"
    assert result["readiness"]["state"] == "Building"


# ── route-level: /view (api-key call site) shape ────────────────────────


def test_view_route_renders_html_from_snapshot(monkeypatch):
    row = _snapshot_row(age=timedelta(minutes=5))
    monkeypatch.setattr(
        WhoopRepository, "get_cockpit_metrics", staticmethod(lambda uid: row)
    )
    monkeypatch.setattr(whoop_route, "today_is_rest_day", _no_rest_day)
    monkeypatch.setattr(
        whoop_route, "_resolve_dashboard_key", lambda key: {"user_id": 1}
    )

    def _boom(uid, today_is_sabbath):
        raise AssertionError("live path should not run when snapshot is fresh")

    monkeypatch.setattr(whoop_route, "_timed_whoop_summary", _boom)

    response = whoop_route.view(key="whatever")

    assert response.status_code == 200
    assert b"Prime" in response.body
